[package]
name = "mpc-node"
version.workspace = true
edition = "2021"

[[bin]]
name = "mpc-node"
path = "src/main.rs"

[features]
default = []
helios = ["dep:helios"]
# utilized for benchmarking the node:
bench = []
# utilized by "integration-tests" package:
test-feature = []
# Show a debug page
debug-page = ["maud"]

[dependencies]
alloy.workspace = true
alloy-dyn-abi.workspace = true
alloy-json-abi.workspace = true
alloy-primitives.workspace = true
alloy-signer-local = "1.0.38"
alloy-sol-types = "1.4.1"
anchor-client.workspace = true
anchor-lang.workspace = true
anyhow.workspace = true
async-trait.workspace = true
axum = "0.7.9"
axum-extra = "0.9.6"
borsh.workspace = true
borsh_sol = { package = "borsh", version = "0.10.4" } # solana anchor requires borsh 0.10
cait-sith.workspace = true
chrono = "0.4.24"
ciborium.workspace = true
clap.workspace = true
deadpool-redis.workspace = true
ed25519-zebra = { version = "4.1", default-features = false, features = ["alloc"] }
futures-util.workspace = true
google-datastore1 = "=5.0.4"
google-secretmanager1 = "5"
helios = { git = "https://github.com/a16z/helios", rev = "e1f9a50f73d7af6f6ae4acf2b663d04aab6adb19", optional = true }
hex.workspace = true
highway = "1.1.0"
hkdf = "0.12.4"
http = "1.1.0"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "=0.24", features = ["http2"] }
k256.workspace = true
local-ip-address = "0.5.4"
lru = "0.13.0"

maud = { version = "0.27.0", optional = true }
mime = "0.3.17"
mpc-contract.workspace = true
mpc-crypto.workspace = true
mpc-keys.workspace = true
mpc-primitives.workspace = true
near-account-id.workspace = true
near-crypto.workspace = true
near-fetch.workspace = true
near-primitives.workspace = true
near-sdk.workspace = true
oauth2 = { version = "4.4.2", default-features = false, features = ["reqwest"] }
opentelemetry = { version = "0.29.0", default-features = false, features = [
    "trace",
] }
opentelemetry-appender-tracing = "0.29.1"
opentelemetry-otlp = { version = "0.29.0" }
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = [
    "trace",
    "rt-tokio",
] }
parity-scale-codec.workspace = true
prometheus = "0.14.0"
rand.workspace = true
redis = "0.27.2"
reqwest.workspace = true
rlp.workspace = true
secrecy = "0.10.3"
semver.workspace = true
serde.workspace = true
serde-aux = { version = "4", default-features = false }
serde_bytes.workspace = true
serde_json.workspace = true
sha3.workspace = true
signet-program.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
solana-transaction-status.workspace = true
sp-core = { version = "38.1", default-features = false, features = ["std"] }
sp-runtime = { version = "44.0.0", default-features = false, features = ["std"] }
sp-state-machine = { version = "0.48", default-features = false, features = ["std"] }
sp-trie = { version = "41.1.0", default-features = false, features = ["std"] }
subxt = { version = "0.44", default-features = false, features = ["jsonrpsee", "native", "unstable-light-client"] }
sysinfo = "0.32.0"
thiserror.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.30.0"
tracing-stackdriver = "0.10.0"
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
mockito = "1.7.0"
tempfile = "3.27.0"
test-log = { version = "0.2.12", features = ["log", "trace"] }
