use super::message::TripleMessage;
use crate::types::TripleProtocol;
use crate::util::AffinePointExt;
use cait_sith::protocol::{Action, InitializationError, Participant, ProtocolError};
use cait_sith::triples::TripleGenerationOutput;
use k256::Secp256k1;
use std::collections::btree_map::Entry;
use std::collections::BTreeMap;

/// Unique number used to identify a specific ongoing triple generation protocol.
/// Without `TripleId` it would be unclear where to route incoming cait-sith triple generation
/// messages.
pub type TripleId = u64;

/// Abstracts how triples are generated by providing a way to request a new triple that will be
/// complete some time in the future and a way to take an already generated triple.
pub struct TripleManager {
    /// Completed unspent triples
    // TODO: I put these into `BTreeMap` so we can potentially use the ordering for choosing which
    // triple to use for consensus, but it might not be necessary.
    triples: BTreeMap<TripleId, TripleGenerationOutput<Secp256k1>>,
    /// Ongoing triple generation protocols
    generators: BTreeMap<TripleId, TripleProtocol>,

    participants: Vec<Participant>,
    me: Participant,
    threshold: usize,
    epoch: u64,
}

impl TripleManager {
    pub fn new(
        participants: Vec<Participant>,
        me: Participant,
        threshold: usize,
        epoch: u64,
    ) -> Self {
        Self {
            triples: BTreeMap::new(),
            generators: BTreeMap::new(),
            participants,
            me,
            threshold,
            epoch,
        }
    }

    /// Returns the number of unspent triples available in the manager.
    pub fn len(&self) -> usize {
        self.triples.len()
    }

    /// Returns the number of unspent triples we will have in the manager once
    /// all ongoing generation protocols complete.
    pub fn potential_len(&self) -> usize {
        self.triples.len() + self.generators.len()
    }

    /// Starts a new Beaver triple generation protocol.
    pub fn generate(&mut self) -> Result<(), InitializationError> {
        let id = rand::random();
        tracing::info!(id, "starting protocol to generate a new triple");
        let protocol: TripleProtocol = Box::new(cait_sith::triples::generate_triple(
            &self.participants,
            self.me,
            self.threshold,
        )?);
        self.generators.insert(id, protocol);
        Ok(())
    }

    /// Take an unspent triple by its id with no way to return it.
    /// It is very important to NOT reuse the same triple twice for two different
    /// protocols.
    pub fn take(&mut self, id: TripleId) -> Option<TripleGenerationOutput<Secp256k1>> {
        self.triples.remove(&id)
    }

    /// Ensures that the triple with the given id is either:
    /// 1) Already generated in which case returns `None`, or
    /// 2) Is currently being generated by `protocol` in which case returns `Some(protocol)`, or
    /// 3) Has never been seen by the manager in which case start a new protocol and returns `Some(protocol)`
    // TODO: What if the triple completed generation and is already spent?
    pub fn get_or_generate(
        &mut self,
        id: TripleId,
    ) -> Result<Option<&mut TripleProtocol>, InitializationError> {
        if self.triples.contains_key(&id) {
            Ok(None)
        } else {
            match self.generators.entry(id) {
                Entry::Vacant(e) => {
                    tracing::info!(id, "joining protocol to generate a new triple");
                    let protocol = cait_sith::triples::generate_triple(
                        &self.participants,
                        self.me,
                        self.threshold,
                    )?;
                    Ok(Some(e.insert(Box::new(protocol))))
                }
                Entry::Occupied(e) => Ok(Some(e.into_mut())),
            }
        }
    }

    /// Pokes all of the ongoing generation protocols and returns a vector of
    /// messages to be sent to the respective participant.
    ///
    /// An empty vector means we cannot progress until we receive a new message.
    pub fn poke(&mut self) -> Result<Vec<(Participant, TripleMessage)>, ProtocolError> {
        let mut messages = Vec::new();
        let mut result = Ok(());
        self.generators.retain(|id, protocol| {
            loop {
                let action = match protocol.poke() {
                    Ok(action) => action,
                    Err(e) => {
                        result = Err(e);
                        break false;
                    }
                };
                match action {
                    Action::Wait => {
                        tracing::debug!("waiting");
                        // Retain protocol until we are finished
                        break true;
                    }
                    Action::SendMany(data) => {
                        for p in &self.participants {
                            messages.push((
                                *p,
                                TripleMessage {
                                    id: *id,
                                    epoch: self.epoch,
                                    from: self.me,
                                    data: data.clone(),
                                },
                            ))
                        }
                    }
                    Action::SendPrivate(p, data) => messages.push((
                        p,
                        TripleMessage {
                            id: *id,
                            epoch: self.epoch,
                            from: self.me,
                            data: data.clone(),
                        },
                    )),
                    Action::Return(output) => {
                        tracing::info!(
                            id,
                            big_a = ?output.1.big_a.to_base58(),
                            big_b = ?output.1.big_b.to_base58(),
                            big_c = ?output.1.big_c.to_base58(),
                            "completed triple generation"
                        );
                        self.triples.insert(*id, output);
                        // Do not retain the protocol
                        break false;
                    }
                }
            }
        });
        result.map(|_| messages)
    }
}
