//! Minting the localnet's key material.
//!
//! `infra/scripts/generate_keys` covers most of this already, but its "Solana" key is a
//! NEAR ed25519 key printed without its prefix, whereas the node calls
//! `Keypair::from_base58_string` on `MPC_SOL_ACCOUNT_SK` and so needs base58 of the full 64
//! byte Solana keypair. It also prints to the terminal rather than writing the env files
//! the cluster reads. Rather than have someone transcribe and convert by hand, the localnet
//! mints its own.
//!
//! These keys protect nothing: they are committed to the repository so that
//! `docker compose up` is reproducible and so the contract's participant set can be derived
//! from the same files the nodes read. Never reuse them anywhere real.

use std::path::Path;

use anyhow::Context;
use solana_sdk::signature::Keypair;
use solana_sdk::signer::Signer;

pub struct GeneratedNode {
    pub index: usize,
    pub account_id: String,
    pub local_address: String,
    /// Every node runs in one container, so each needs a port of its own.
    pub web_port: u16,
    pub account_sk: near_crypto::SecretKey,
    pub sign_sk: near_crypto::SecretKey,
    pub cipher_sk: mpc_keys::hpke::SecretKey,
    pub solana_sk: Keypair,
}

impl GeneratedNode {
    fn to_env_file(&self) -> String {
        format!(
            "# Node {index} of the local MPC cluster.\n\
             #\n\
             # Generated by `mpc-localnet keygen`. These keys are committed on purpose so the\n\
             # cluster starts up reproducibly, and they protect nothing. Never reuse them.\n\
             #\n\
             # The bootstrap derives every public value it registers in the MPC contract from\n\
             # this file, so the contract cannot drift out of step with what the node runs.\n\
             MPC_ACCOUNT_ID={account_id}\n\
             MPC_ACCOUNT_SK={account_sk}\n\
             MPC_SIGN_SK={sign_sk}\n\
             MPC_CIPHER_SK={cipher_sk}\n\
             MPC_LOCAL_ADDRESS={local_address}\n\
             MPC_SOL_ACCOUNT_SK={solana_sk}\n\
             MPC_WEB_PORT={web_port}\n",
            index = self.index,
            account_id = self.account_id,
            account_sk = self.account_sk,
            sign_sk = self.sign_sk,
            cipher_sk = hex::encode(self.cipher_sk.to_bytes()),
            local_address = self.local_address,
            solana_sk = self.solana_sk.to_base58_string(),
            web_port = self.web_port,
        )
    }
}

fn generate_one(
    index: usize,
    account_template: &str,
    address_template: &str,
    base_port: u16,
) -> GeneratedNode {
    let placeholder = index.to_string();
    let web_port = base_port + index as u16;
    let (cipher_sk, _cipher_pk) = mpc_keys::hpke::generate();
    GeneratedNode {
        index,
        account_id: account_template.replace("{i}", &placeholder),
        local_address: address_template
            .replace("{i}", &placeholder)
            .replace("{port}", &web_port.to_string()),
        web_port,
        account_sk: near_crypto::SecretKey::from_random(near_crypto::KeyType::ED25519),
        sign_sk: near_crypto::SecretKey::from_random(near_crypto::KeyType::ED25519),
        cipher_sk,
        solana_sk: Keypair::new(),
    }
}

pub fn write_all(
    out_dir: &Path,
    count: usize,
    account_template: &str,
    address_template: &str,
    base_port: u16,
) -> anyhow::Result<Vec<GeneratedNode>> {
    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("creating {}", out_dir.display()))?;

    let nodes: Vec<GeneratedNode> = (0..count)
        .map(|index| generate_one(index, account_template, address_template, base_port))
        .collect();

    let mut sorted: Vec<&str> = nodes.iter().map(|node| node.account_id.as_str()).collect();
    sorted.sort();
    for (position, account_id) in sorted.iter().enumerate() {
        if *account_id != nodes[position].account_id {
            anyhow::bail!(
                "the account template {account_template} produces ids whose lexicographic order \
                 differs from their numeric order ({} sorts at position {position}). The contract \
                 assigns participant ids in sorted order, so this would hand each node the key \
                 share of a different participant.",
                account_id,
            );
        }
    }

    for node in &nodes {
        let path = out_dir.join(format!("node{}.env", node.index));
        std::fs::write(&path, node.to_env_file())
            .with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {}", path.display());
        println!("  account:   {}", node.account_id);
        println!("  address:   {}", node.local_address);
        println!("  solana pk: {}", node.solana_sk.pubkey());
    }
    Ok(nodes)
}
