//! Preloading the cluster's Beaver triples and presignatures.
//!
//! A signature consumes one presignature, which consumes one pair of triples, and both are
//! produced by multi-round protocols between the nodes. Writing a dealt set straight into
//! Redis at bootstrap means every node holds the same material from the moment it starts, on
//! every run, which is what makes a failure here reproducible.
//!
//! It does not make the cluster reach its first signature any sooner. Cold start to first
//! signature measures 18 s and 20 s with this on, 17 s and 18 s with it off, on the committed
//! three-node profile: at `min_triples: 8` the nodes generate what they need in seconds.
//! `AGENTS.md` carries the numbers. Do not sell this as a speed-up.
//!
//! The material comes from `integration-tests/src/mpc_fixture/3_nodes.json`, the same file
//! the committed key shares come from, so the triples are shares under the very key the
//! cluster runs. Handing out shares of a triple generated by one party is only sound when
//! that party is trusted to forget them. It is a local development cluster whose key
//! material is committed to the repository, so there is nothing here to protect.
//!
//! ## The Redis layout is duplicated, and that is a liability
//!
//! `mpc_node::storage::{triple_storage, presignature_storage}` own these keys. Calling them
//! would mean compiling `mpc-node` into the bootstrap image, which costs a second full build
//! of the node for four Redis commands. So the layout is written out again here, and the tests
//! at the foot of this file read the node's own source to check that the copy still matches.
//! Delete this module's constants and call the real storage API if `mpc-node` ever becomes a
//! dependency here for another reason.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{anyhow, Context};
use redis::AsyncCommands;
use serde::Deserialize;
use serde_json::{json, Value};

use crate::nodes::NodeSpec;

/// Namespace segment every storage key carries, mirroring `STORAGE_VERSION` in
/// `chain-signatures/node/src/storage/mod.rs`. Bumping it there is how the node abandons
/// material written under an incompatible format, so a stale copy here would preload into a
/// namespace nothing reads.
const STORAGE_VERSION: &str = "v9";

/// The fixture as the integration tests write it.
///
/// The two maps are indexed by holder first and owner second: `triples[me][owner]` is the
/// set of shares node *me* holds of triples that node *owner* is responsible for spending.
/// Only the envelope is typed. Each share and public value passes through as opaque JSON,
/// which keeps this module out of the way of the curve types entirely: whatever the node
/// serialises, the fixture holds, and the fixture is what gets written back.
#[derive(Deserialize)]
struct Fixture {
    #[serde(default)]
    triples: BTreeMap<u32, BTreeMap<u32, Vec<FixtureTriple>>>,
    #[serde(default)]
    presignatures: BTreeMap<u32, BTreeMap<u32, Vec<Value>>>,
}

#[derive(Deserialize)]
struct FixtureTriple {
    id: u64,
    share: Value,
    public: Value,
}

/// How much was written, for the caller to log.
pub struct Loaded {
    pub triple_pairs: usize,
    pub presignatures: usize,
}

/// Write the fixture's triples and presignatures into Redis for every node.
///
/// Returns `None` when the cluster already holds material, so that re-running the bootstrap
/// against a live stack leaves it alone. Both stores are checked: a node that has spent its
/// way through one but not the other is left alone too, since topping up mid-life would
/// collide with ids the cluster has already retired.
pub async fn run(
    fixture_path: &Path,
    redis_url: &str,
    nodes: &[NodeSpec],
    threshold: usize,
) -> anyhow::Result<Option<Loaded>> {
    let text = std::fs::read_to_string(fixture_path)
        .with_context(|| format!("reading the fixture at {}", fixture_path.display()))?;
    let fixture: Fixture = serde_json::from_str(&text)
        .with_context(|| format!("parsing the fixture at {}", fixture_path.display()))?;

    check_shape(&fixture, nodes.len(), threshold)?;

    let client = redis::Client::open(redis_url)
        .with_context(|| format!("opening a redis client for {redis_url}"))?;
    let mut conn = client
        .get_multiplexed_async_connection()
        .await
        .with_context(|| format!("connecting to redis at {redis_url}"))?;

    for node in nodes {
        let triples: usize = conn.hlen(triple_key(node)).await?;
        let presignatures: usize = conn.hlen(presignature_key(node)).await?;
        if triples > 0 || presignatures > 0 {
            tracing::info!(
                account_id = %node.account_id,
                triples,
                presignatures,
                "redis already holds protocol material, leaving the stockpile alone",
            );
            return Ok(None);
        }
    }

    let mut pipe = redis::pipe();
    let mut triple_pairs = 0;
    let mut presignatures = 0;

    for (owner, pairs) in pairs_by_owner(&fixture, nodes.len()) {
        for (index, node) in nodes.iter().enumerate() {
            let held = index as u32;
            let by_id: BTreeMap<u64, &FixtureTriple> = fixture.triples[&held][&owner]
                .iter()
                .map(|triple| (triple.id, triple))
                .collect();

            for [first, second] in &pairs {
                let pair = json!({
                    "id": first,
                    "triple0": triple_body(by_id[first]),
                    "triple1": triple_body(by_id[second]),
                });
                pipe.hset(triple_key(node), first, pair.to_string()).ignore();
                pipe.sadd(triple_owner_key(node, owner), first).ignore();
                pipe.sadd(triple_owners_key(node), triple_owner_key(node, owner))
                    .ignore();
            }
        }
        triple_pairs += pairs.len();
    }

    for (owner, ids) in shared_presignature_ids(&fixture, nodes.len())? {
        for (index, node) in nodes.iter().enumerate() {
            let held = index as u32;
            for presignature in &fixture.presignatures[&held][&owner] {
                let id = presignature_id(presignature)?;
                if !ids.contains(&id) {
                    continue;
                }
                pipe.hset(presignature_key(node), id, presignature.to_string())
                    .ignore();
                pipe.sadd(presignature_owner_key(node, owner), id).ignore();
                pipe.sadd(
                    presignature_owners_key(node),
                    presignature_owner_key(node, owner),
                )
                .ignore();
            }
        }
        presignatures += ids.len();
    }

    pipe.query_async::<()>(&mut conn)
        .await
        .context("writing the stockpile into redis")?;

    Ok(Some(Loaded {
        triple_pairs,
        presignatures,
    }))
}

/// The triple as the node stores it, which is the fixture entry without its id.
fn triple_body(triple: &FixtureTriple) -> Value {
    json!({ "share": triple.share, "public": triple.public })
}

/// Pair up each owner's triples so that every node pairs them identically.
///
/// A pair is spent as a unit and is addressed by the id of its first triple, so the nodes
/// have to agree on which two triples make it up. Pairing each node's own list in stored
/// order, which is what `MpcFixtureBuilder` does, does not give that. In the committed 3-node
/// file, participant 2 holds shares of owners 0 and 2 that the other two do not, interleaved
/// with the ones they all hold, so the cut shifts: for each of those owners one pair id ends
/// up naming a different second triple on participant 2 than on participant 0, and for owner 0
/// participant 0 forms a pair participant 2 has never seen.
///
/// Intersecting the ids and sorting them removes the ambiguity: every node sees the same
/// list and so cuts it the same way. An odd one out is dropped.
fn pairs_by_owner(fixture: &Fixture, node_count: usize) -> Vec<(u32, Vec<[u64; 2]>)> {
    let mut out = Vec::new();
    for owner in 0..node_count as u32 {
        let mut shared: Option<BTreeSet<u64>> = None;
        for held in 0..node_count as u32 {
            let ids: BTreeSet<u64> = fixture.triples[&held][&owner]
                .iter()
                .map(|triple| triple.id)
                .collect();
            shared = Some(match shared {
                None => ids,
                Some(common) => common.intersection(&ids).copied().collect(),
            });
        }
        let shared = shared.unwrap_or_default();
        let pairs = shared
            .iter()
            .copied()
            .collect::<Vec<_>>()
            .chunks_exact(2)
            .map(|pair| [pair[0], pair[1]])
            .collect();
        out.push((owner, pairs));
    }
    out
}

/// The presignature ids every node holds a share of, per owner. A presignature only one node
/// knows about is one the others cannot take part in spending.
fn shared_presignature_ids(
    fixture: &Fixture,
    node_count: usize,
) -> anyhow::Result<Vec<(u32, BTreeSet<u64>)>> {
    let mut out = Vec::new();
    for owner in 0..node_count as u32 {
        let mut shared: Option<BTreeSet<u64>> = None;
        for held in 0..node_count as u32 {
            let mut ids = BTreeSet::new();
            for presignature in &fixture.presignatures[&held][&owner] {
                ids.insert(presignature_id(presignature)?);
            }
            shared = Some(match shared {
                None => ids,
                Some(common) => common.intersection(&ids).copied().collect(),
            });
        }
        out.push((owner, shared.unwrap_or_default()));
    }
    Ok(out)
}

/// Which owners each holder carries material for, with the material itself dropped.
fn index_shape<T>(by_holder: &BTreeMap<u32, BTreeMap<u32, Vec<T>>>) -> BTreeMap<u32, BTreeSet<u32>> {
    by_holder
        .iter()
        .map(|(held, by_owner)| (*held, by_owner.keys().copied().collect()))
        .collect()
}

fn presignature_id(presignature: &Value) -> anyhow::Result<u64> {
    presignature
        .get("id")
        .and_then(Value::as_u64)
        .ok_or_else(|| anyhow!("a presignature in the fixture has no numeric id"))
}

/// Reject a fixture that was not built for this cluster.
///
/// A fixture for a different participant set or threshold produces shares that no quorum can
/// combine. The cluster would still come up reporting itself as running, and every signature
/// would time out, which is the same expensive failure the key share ordering check exists to
/// prevent.
fn check_shape(fixture: &Fixture, node_count: usize, threshold: usize) -> anyhow::Result<()> {
    let expected: BTreeSet<u32> = (0..node_count as u32).collect();

    // Everything downstream indexes both maps by holder and then by owner, so every
    // combination has to be present before any of it is read.
    for (label, by_holder) in [
        ("triples", index_shape(&fixture.triples)),
        ("presignatures", index_shape(&fixture.presignatures)),
    ] {
        let holders: BTreeSet<u32> = by_holder.keys().copied().collect();
        if holders != expected {
            anyhow::bail!(
                "the fixture holds {label} for participants {holders:?}, but this cluster has \
                 {node_count} nodes and so needs {expected:?}"
            );
        }
        for (held, owners) in &by_holder {
            if *owners != expected {
                anyhow::bail!(
                    "participant {held} holds {label} owned by {owners:?}, but this cluster \
                     needs {expected:?}"
                );
            }
        }
    }

    for by_owner in fixture.triples.values() {
        for triples in by_owner.values() {
            for triple in triples {
                let declared = triple
                    .public
                    .get("threshold")
                    .and_then(Value::as_u64)
                    .ok_or_else(|| anyhow!("triple {} has no threshold", triple.id))?;
                if declared as usize != threshold {
                    anyhow::bail!(
                        "triple {} was dealt at threshold {declared}, but this cluster runs at \
                         threshold {threshold}",
                        triple.id
                    );
                }
            }
        }
    }

    Ok(())
}

fn triple_key(node: &NodeSpec) -> String {
    format!("triples:{STORAGE_VERSION}:{}", node.account_id)
}

fn triple_owners_key(node: &NodeSpec) -> String {
    format!("triples_owners:{STORAGE_VERSION}:{}", node.account_id)
}

fn presignature_key(node: &NodeSpec) -> String {
    format!("presignatures:{STORAGE_VERSION}:{}", node.account_id)
}

fn presignature_owners_key(node: &NodeSpec) -> String {
    format!("presignatures_owners:{STORAGE_VERSION}:{}", node.account_id)
}

/// The per-owner set, which the node reads to find what a given participant is holding for
/// it. `owner_key` in `chain-signatures/node/src/storage/mod.rs` builds the same string.
fn triple_owner_key(node: &NodeSpec, owner: u32) -> String {
    format!("{}:p{owner}", triple_owners_key(node))
}

fn presignature_owner_key(node: &NodeSpec, owner: u32) -> String {
    format!("{}:p{owner}", presignature_owners_key(node))
}

#[cfg(test)]
mod tests {
    use super::*;

    const NODE_STORAGE_MOD: &str =
        include_str!("../../../chain-signatures/node/src/storage/mod.rs");
    const NODE_TRIPLE_STORAGE: &str =
        include_str!("../../../chain-signatures/node/src/storage/triple_storage.rs");
    const FIXTURE: &str =
        include_str!("../../../integration-tests/src/mpc_fixture/3_nodes.json");

    fn fixture() -> Fixture {
        serde_json::from_str(FIXTURE).expect("the committed fixture must parse")
    }

    /// The namespace this module writes under has to be the one the node reads from. Parsing
    /// it out of the node's own source is what makes a bump there fail here.
    #[test]
    fn storage_version_matches_the_node() {
        assert!(
            !NODE_STORAGE_MOD.is_empty(),
            "the node's storage module is empty, so this check is inspecting nothing"
        );
        const DECLARATION: &str = "pub const STORAGE_VERSION: &str = ";
        let line = NODE_STORAGE_MOD
            .lines()
            .find(|line| line.trim_start().starts_with(DECLARATION))
            .expect(
                "the node no longer declares STORAGE_VERSION where this check looks for it, so \
                 the preloaded material can no longer be shown to land where the node reads",
            );
        let declared = line
            .split('"')
            .nth(1)
            .expect("STORAGE_VERSION is not a string literal any more");
        assert_eq!(
            declared, STORAGE_VERSION,
            "the node stores under {declared} while the stockpile writes under {STORAGE_VERSION}, \
             so every preloaded triple would be invisible to it",
        );
    }

    /// `triple_body` builds the envelope by hand, so the field names it writes have to be the
    /// ones `TriplePair` derives its `Deserialize` from. Renaming a field there without
    /// renaming it here would leave the node rejecting every preloaded pair.
    #[test]
    fn triple_pair_fields_match_the_node() {
        let declaration = NODE_TRIPLE_STORAGE
            .split("pub struct TriplePair {")
            .nth(1)
            .and_then(|rest| rest.split('}').next())
            .expect("the node no longer declares TriplePair where this check looks for it");
        for field in ["id", "triple0", "triple1"] {
            assert!(
                declaration.contains(&format!("pub {field}:")),
                "TriplePair has no {field} field any more, but the stockpile still writes one",
            );
        }
        let written = triple_body(&FixtureTriple {
            id: 1,
            share: json!({}),
            public: json!({}),
        });
        for field in ["share", "public"] {
            assert!(
                written.get(field).is_some(),
                "the triple body no longer carries {field}",
            );
        }
    }

    /// The whole point of intersecting and sorting: every node has to cut the same list the
    /// same way, or a pair one node spends is a pair another cannot recognise.
    #[test]
    fn every_node_pairs_the_committed_fixture_identically() {
        let fixture = fixture();
        let pairs = pairs_by_owner(&fixture, 3);
        assert!(!pairs.is_empty(), "the fixture yielded no owners to pair");

        let mut total = 0;
        for (owner, owner_pairs) in &pairs {
            assert!(
                !owner_pairs.is_empty(),
                "owner {owner} contributed no pairs, so this check is inspecting nothing"
            );
            total += owner_pairs.len();
            for held in 0..3u32 {
                let ids: BTreeSet<u64> = fixture.triples[&held][owner]
                    .iter()
                    .map(|triple| triple.id)
                    .collect();
                for [first, second] in owner_pairs {
                    assert!(
                        ids.contains(first) && ids.contains(second),
                        "participant {held} holds no share of pair [{first}, {second}] owned by \
                         {owner}, so it could not take part in spending it",
                    );
                }
            }
        }
        assert!(
            total >= crate::near::MIN_TRIPLES as usize,
            "the fixture yields {total} pairs, too few to clear the {} the contract is \
             initialised with, so the nodes would generate more before serving anything",
            crate::near::MIN_TRIPLES,
        );
    }

    /// Presignatures are spent whole, so one every node does not hold is one no quorum can
    /// combine. Intersecting drops those, and enough survive to serve the first requests.
    #[test]
    fn every_node_shares_the_committed_presignatures() {
        let fixture = fixture();
        let by_owner = shared_presignature_ids(&fixture, 3).expect("intersecting must succeed");
        assert!(!by_owner.is_empty(), "the fixture yielded no owners");

        let mut total = 0;
        for (owner, ids) in &by_owner {
            assert!(
                !ids.is_empty(),
                "owner {owner} contributed no presignatures, so this check inspects nothing"
            );
            total += ids.len();
            for held in 0..3u32 {
                let held_ids: BTreeSet<u64> = fixture.presignatures[&held][owner]
                    .iter()
                    .map(|p| presignature_id(p).expect("fixture presignatures carry ids"))
                    .collect();
                assert!(
                    ids.is_subset(&held_ids),
                    "participant {held} is missing a presignature owned by {owner}",
                );
            }
        }
        assert!(
            total >= crate::near::MIN_PRESIGNATURES as usize,
            "the fixture yields {total} presignatures, too few to clear the {} the contract is \
             initialised with",
            crate::near::MIN_PRESIGNATURES,
        );
    }

    /// The committed fixture is a 3 node, threshold 2 deal, which is what the localnet runs.
    #[test]
    fn committed_fixture_matches_the_cluster() {
        check_shape(&fixture(), 3, 2).expect("the committed fixture must fit the localnet");
        assert!(
            check_shape(&fixture(), 3, 3).is_err(),
            "a threshold mismatch has to be rejected, otherwise every signature times out"
        );
        assert!(
            check_shape(&fixture(), 5, 2).is_err(),
            "a participant count mismatch has to be rejected"
        );
    }
}
