use alloy_primitives::{keccak256, U256};
use alloy_sol_types::SolValue;

/// Computes a request ID based on the provided parameters. The request ID is generated by encoding the parameters using ABI encoding and then hashing the result using Keccak256.
#[allow(clippy::too_many_arguments)]
pub fn compute_request_id(
    sender: &str,
    payload: &[u8; 32],
    path: &str,
    key_version: u32,
    chain_id: &str,
    algo: &str,
    dest: &str,
    params: &str,
) -> [u8; 32] {
    let encoded = (
        sender,
        payload.to_vec(),
        path,
        U256::from(key_version),
        chain_id,
        algo,
        dest,
        params,
    )
        .abi_encode_params();

    keccak256(&encoded).0
}

/// Computes the Keccak256 hash of the given payload.
pub fn hash_payload(data: &[u8]) -> [u8; 32] {
    keccak256(data).0
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Returns a tuple of default arguments for testing the `compute_request_id` function.
    fn default_args() -> (
        &'static str,
        [u8; 32],
        &'static str,
        u32,
        &'static str,
        &'static str,
        &'static str,
        &'static str,
    ) {
        (
            "sender.near",
            [0u8; 32],
            "m/44'/397'/0'",
            0,
            "ethereum",
            "secp256k1",
            "0xDEAD",
            "",
        )
    }

    #[test]
    fn compute_request_id_returns_32_bytes() {
        let (sender, payload, path, kv, chain, algo, dest, params) = default_args();
        let id = compute_request_id(sender, &payload, path, kv, chain, algo, dest, params);
        assert_eq!(id.len(), 32);
    }

    #[test]
    fn compute_request_id_is_deterministic() {
        let (sender, payload, path, kv, chain, algo, dest, params) = default_args();
        let id1 = compute_request_id(sender, &payload, path, kv, chain, algo, dest, params);
        let id2 = compute_request_id(sender, &payload, path, kv, chain, algo, dest, params);
        assert_eq!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_sender() {
        let (_, payload, path, kv, chain, algo, dest, params) = default_args();
        let id1 = compute_request_id("alice.near", &payload, path, kv, chain, algo, dest, params);
        let id2 = compute_request_id("bob.near", &payload, path, kv, chain, algo, dest, params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_payload() {
        let (sender, _, path, kv, chain, algo, dest, params) = default_args();
        let payload_a = [0u8; 32];
        // Set the last byte to 1 for payload_b
        let mut payload_b = [0u8; 32];
        payload_b[31] = 1;
        let id1 = compute_request_id(sender, &payload_a, path, kv, chain, algo, dest, params);
        let id2 = compute_request_id(sender, &payload_b, path, kv, chain, algo, dest, params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_path() {
        let (sender, payload, _, kv, chain, algo, dest, params) = default_args();
        let id1 = compute_request_id(
            sender,
            &payload,
            "m/44'/397'/0'",
            kv,
            chain,
            algo,
            dest,
            params,
        );
        let id2 = compute_request_id(
            sender,
            &payload,
            "m/44'/397'/1'",
            kv,
            chain,
            algo,
            dest,
            params,
        );
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_key_version() {
        let (sender, payload, path, _, chain, algo, dest, params) = default_args();
        let id1 = compute_request_id(sender, &payload, path, 0, chain, algo, dest, params);
        let id2 = compute_request_id(sender, &payload, path, 1, chain, algo, dest, params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_chain_id() {
        let (sender, payload, path, kv, _, algo, dest, params) = default_args();
        let id1 = compute_request_id(sender, &payload, path, kv, "ethereum", algo, dest, params);
        let id2 = compute_request_id(sender, &payload, path, kv, "near", algo, dest, params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_algo() {
        let (sender, payload, path, kv, chain, _, dest, params) = default_args();
        let id1 = compute_request_id(sender, &payload, path, kv, chain, "secp256k1", dest, params);
        let id2 = compute_request_id(sender, &payload, path, kv, chain, "ed25519", dest, params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_dest() {
        let (sender, payload, path, kv, chain, algo, _, params) = default_args();
        let id1 = compute_request_id(sender, &payload, path, kv, chain, algo, "0xFOO", params);
        let id2 = compute_request_id(sender, &payload, path, kv, chain, algo, "0xBAR", params);
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_differs_by_params() {
        let (sender, payload, path, kv, chain, algo, dest, _) = default_args();
        let id1 = compute_request_id(sender, &payload, path, kv, chain, algo, dest, "");
        let id2 = compute_request_id(sender, &payload, path, kv, chain, algo, dest, "extra");
        assert_ne!(id1, id2);
    }

    #[test]
    fn compute_request_id_key_version_max() {
        let (sender, payload, path, _, chain, algo, dest, params) = default_args();
        // u32::MAX should not panic
        let id = compute_request_id(sender, &payload, path, u32::MAX, chain, algo, dest, params);
        assert_eq!(id.len(), 32);
    }

    #[test]
    fn hash_payload_empty() {
        // keccak256("")
        let expected: [u8; 32] = [
            0xc5, 0xd2, 0x46, 0x01, 0x86, 0xf7, 0x23, 0x3c, 0x92, 0x7e, 0x7d, 0xb2, 0xdc, 0xc7,
            0x03, 0xc0, 0xe5, 0x00, 0xb6, 0x53, 0xca, 0x82, 0x27, 0x3b, 0x7b, 0xfa, 0xd8, 0x04,
            0x5d, 0x85, 0xa4, 0x70,
        ];
        assert_eq!(hash_payload(&[]), expected);
    }

    #[test]
    fn hash_payload_known_value() {
        let result = hash_payload(b"hello");
        // Must be 32 bytes and deterministic
        assert_eq!(result.len(), 32);
        // Same input must return the same hash
        assert_eq!(result, hash_payload(b"hello"));
    }

    #[test]
    fn hash_payload_single_byte() {
        let a = hash_payload(&[0x00]);
        let b = hash_payload(&[0x01]);
        assert_ne!(a, b);
        assert_eq!(a, hash_payload(&[0x00]));
    }
}
