use alloy_primitives::{keccak256, U256};
use alloy_sol_types::SolValue;

/// Computes a request ID based on the provided parameters. The request ID is generated by encoding the parameters using ABI encoding and then hashing the result using Keccak256.
pub fn compute_request_id(
    sender: &str,
    payload: &[u8; 32],
    path: &str,
    key_version: u32,
    chain_id: &str,
    algo: &str,
    dest: &str,
    params: &str,
) -> [u8; 32] {
    let encoded = (
        sender,
        payload.to_vec(),
        path,
        U256::from(key_version),
        chain_id,
        algo,
        dest,
        params,
    )
        .abi_encode();

    keccak256(&encoded).0
}

/// Computes the Keccak256 hash of the given payload.
pub fn hash_payload(data: &[u8]) -> [u8; 32] {
    keccak256(data).0
}
