[package]
name = "mpc-deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
borsh = "1.5.0"
clap = { version = "4.2", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
near-workspaces = { git = "https://github.com/near/near-workspaces-rs", branch = "node/1.40" }
tokio = { version = "1", features = ["full"] }

# crypto dependencies
k256 = { version = "0.13.1", features = [
    "sha256",
    "ecdsa",
    "serde",
    "arithmetic",
    "expose-field",
] }
ecdsa = { version = "0.16.9", features = ["digest", "hazmat"] }
signature = "2.2.0"
digest = "0.10.7"

# local dependencies
mpc-contract = { path = "../../../chain-signatures/contract" }

[workspace]
