[target.x86_64-apple-darwin]
rustflags = [
  "-L", "/opt/homebrew/lib",
  "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-L", "/opt/homebrew/lib",
  "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

# This is basically a prebuild script used to build the node/contract before running
# integration-tests.
[target.'cfg(not(target = "wasm32-unknown-unknown"))']
runner = "./setup.sh"

[alias]
build-node = "build -p mpc-node --release"
build-test = "build -p integration-tests --tests"
test-i = "test -p integration-tests --jobs 1 -- --test-threads 1 --show-output"
test-unit = "test --workspace --exclude integration-tests -- --show-output"
test-basic = "test -p integration-tests -- --show-output --exact cases::test_signature_basic"
