[package]
name = "signet-program"
version = "0.1.0"
description = "Minimal types for Solana indexer integration"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "signet_program"

[dependencies]
anchor-lang = "0.31.0"