[package]
name = "mpc-keys"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh.workspace = true
hex.workspace = true
hpke = { version = "0.11", features = ["serde_impls", "std"] }
serde.workspace = true
rand.workspace = true
