//! SGN1 wire format: parsing Midnight `Misc` contract events into request parts.
//!
//! The normative spec lives in the demo repo at `docs/signet-midnight-events.md`.
//! Every event payload is `requestId(32) || tail(224)`; the requestId is the
//! SHA-256 of the concatenated tails of all parts of a request. Golden vectors
//! in `tests/goldens/` (generated by executing the compiled contract) pin every
//! layout asserted here.

use sha2::{Digest, Sha256};

/// Bytes<32> event name.
pub const NAME_LEN: usize = 32;
/// Bytes<256> event payload.
pub const PAYLOAD_LEN: usize = 256;
/// requestId prefix of every payload.
pub const RID_LEN: usize = 32;
/// Fixed part-body tail (Compact `serialize<Part, 224>`).
pub const TAIL_LEN: usize = 224;
/// Largest part count of any request kind (`sign_bidirectional`), used to bound
/// the reassembly buffer and the resume over-fetch window.
pub const MAX_PARTS: usize = 5;

/// The four SGN1 request kinds, keyed by the event-name grammar.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RequestKind {
    Sign,
    SignBidirectional,
    Respond,
    RespondBidirectional,
}

impl RequestKind {
    pub const fn part_count(self) -> usize {
        match self {
            RequestKind::Sign => 1,
            RequestKind::SignBidirectional => 5,
            RequestKind::Respond => 1,
            RequestKind::RespondBidirectional => 2,
        }
    }
}

/// A single parsed `Misc` event: its (kind, part index) and the payload split
/// into requestId + tail.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EventPart {
    pub kind: RequestKind,
    /// 1-based index within the request (`i` of `i/N`).
    pub part_index: usize,
    pub request_id: [u8; RID_LEN],
    pub tail: [u8; TAIL_LEN],
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum WireError {
    #[error("event name is not valid ASCII")]
    NonAsciiName,
    #[error("unrecognized SGN1 event name: {0:?}")]
    UnknownName(String),
    #[error("payload is {0} bytes, expected {PAYLOAD_LEN}")]
    BadPayloadLen(usize),
    #[error("part index {index} out of range 1..={count}")]
    PartIndexOutOfRange { index: usize, count: usize },
}

/// Decode the event name (zero-padding stripped) into (kind, part index).
fn parse_name(name: &[u8]) -> Result<(RequestKind, usize), WireError> {
    // Trailing zero padding is not ASCII text; strip it before decoding.
    let end = name.iter().position(|&b| b == 0).unwrap_or(name.len());
    let ascii = std::str::from_utf8(&name[..end]).map_err(|_| WireError::NonAsciiName)?;

    let single = |kind: RequestKind| Ok((kind, 1usize));
    match ascii {
        "SGN1:SIGN" => single(RequestKind::Sign),
        "SGN1:RESP" => single(RequestKind::Respond),
        other => {
            // Chunked forms: "SGN1:SIGNBI:<i>/5" and "SGN1:RESPBI:<i>/2".
            let (kind, rest) = if let Some(rest) = other.strip_prefix("SGN1:SIGNBI:") {
                (RequestKind::SignBidirectional, rest)
            } else if let Some(rest) = other.strip_prefix("SGN1:RESPBI:") {
                (RequestKind::RespondBidirectional, rest)
            } else {
                return Err(WireError::UnknownName(ascii.to_string()));
            };
            let (idx, total) = rest
                .split_once('/')
                .ok_or_else(|| WireError::UnknownName(ascii.to_string()))?;
            let index: usize = idx
                .parse()
                .map_err(|_| WireError::UnknownName(ascii.to_string()))?;
            let total: usize = total
                .parse()
                .map_err(|_| WireError::UnknownName(ascii.to_string()))?;
            if total != kind.part_count() || index < 1 || index > total {
                return Err(WireError::PartIndexOutOfRange {
                    index,
                    count: kind.part_count(),
                });
            }
            Ok((kind, index))
        }
    }
}

impl EventPart {
    /// Parse a raw `Misc` event (name + payload bytes) into an `EventPart`.
    ///
    /// `name` and `payload` are the decoded (un-hex) bytes exactly as the ledger
    /// records them: zero-padded to 32 and 256 bytes respectively.
    pub fn parse(name: &[u8], payload: &[u8]) -> Result<Self, WireError> {
        if payload.len() != PAYLOAD_LEN {
            return Err(WireError::BadPayloadLen(payload.len()));
        }
        let (kind, part_index) = parse_name(name)?;
        let mut request_id = [0u8; RID_LEN];
        request_id.copy_from_slice(&payload[..RID_LEN]);
        let mut tail = [0u8; TAIL_LEN];
        tail.copy_from_slice(&payload[RID_LEN..]);
        Ok(Self {
            kind,
            part_index,
            request_id,
            tail,
        })
    }
}

/// The requestId of a request is SHA-256 over the concatenation of its parts'
/// tails, in part order. Verified against `persistentHash` in the goldens.
pub fn recompute_request_id(tails: &[[u8; TAIL_LEN]]) -> [u8; RID_LEN] {
    let mut hasher = Sha256::new();
    for tail in tails {
        hasher.update(tail);
    }
    hasher.finalize().into()
}

/// Little-endian `Uint<N>` decode from a fixed slice into u128 (N ≤ 16).
pub fn le_uint(bytes: &[u8]) -> u128 {
    let mut acc = 0u128;
    for (i, &b) in bytes.iter().enumerate().take(16) {
        acc |= (b as u128) << (8 * i);
    }
    acc
}

/// Strip trailing zero bytes and decode as UTF-8 (ASCII wire fields).
pub fn ascii_field(bytes: &[u8]) -> String {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(bytes.len());
    String::from_utf8_lossy(&bytes[..end]).into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_goldens::{golden, hex32, payload_bytes};

    #[test]
    fn parses_sign_name_and_split() {
        let g = golden("sign.json");
        let ev = &g["cases"][0]["events"][0];
        let name = hex::decode(ev["name"].as_str().unwrap()).unwrap();
        let payload = payload_bytes(ev);
        let part = EventPart::parse(&name, &payload).unwrap();
        assert_eq!(part.kind, RequestKind::Sign);
        assert_eq!(part.part_index, 1);
        assert_eq!(
            part.request_id,
            hex32(g["cases"][0]["requestId"].as_str().unwrap())
        );
    }

    #[test]
    fn sign_request_id_is_sha256_of_tail() {
        let g = golden("sign.json");
        let ev = &g["cases"][0]["events"][0];
        let payload = payload_bytes(ev);
        let part = EventPart::parse(
            &hex::decode(ev["name"].as_str().unwrap()).unwrap(),
            &payload,
        )
        .unwrap();
        assert_eq!(
            recompute_request_id(&[part.tail]),
            hex32(g["cases"][0]["requestId"].as_str().unwrap())
        );
    }

    #[test]
    fn signbi_five_parts_recompute_shared_rid() {
        let g = golden("sign_bidirectional.json");
        let events = g["cases"][0]["events"].as_array().unwrap();
        assert_eq!(events.len(), 5);
        let rid = hex32(g["cases"][0]["requestId"].as_str().unwrap());
        let mut tails = Vec::new();
        for (i, ev) in events.iter().enumerate() {
            let name = hex::decode(ev["name"].as_str().unwrap()).unwrap();
            let part = EventPart::parse(&name, &payload_bytes(ev)).unwrap();
            assert_eq!(part.kind, RequestKind::SignBidirectional);
            assert_eq!(part.part_index, i + 1);
            assert_eq!(part.request_id, rid);
            tails.push(part.tail);
        }
        assert_eq!(recompute_request_id(&tails), rid);
    }

    #[test]
    fn respond_and_respond_bi_names() {
        let r = golden("respond.json");
        let rev = &r["cases"][0]["events"][0];
        let part = EventPart::parse(
            &hex::decode(rev["name"].as_str().unwrap()).unwrap(),
            &payload_bytes(rev),
        )
        .unwrap();
        assert_eq!(part.kind, RequestKind::Respond);

        let rb = golden("respond_bidirectional.json");
        let events = rb["cases"][0]["events"].as_array().unwrap();
        assert_eq!(events.len(), 2);
        for (i, ev) in events.iter().enumerate() {
            let part = EventPart::parse(
                &hex::decode(ev["name"].as_str().unwrap()).unwrap(),
                &payload_bytes(ev),
            )
            .unwrap();
            assert_eq!(part.kind, RequestKind::RespondBidirectional);
            assert_eq!(part.part_index, i + 1);
        }
    }

    #[test]
    fn rejects_unknown_and_malformed_names() {
        let payload = [0u8; PAYLOAD_LEN];
        assert!(matches!(
            EventPart::parse(b"SGN1:BOGUS", &payload),
            Err(WireError::UnknownName(_))
        ));
        // wrong total in the fraction
        let mut name = [0u8; NAME_LEN];
        name[..15].copy_from_slice(b"SGN1:SIGNBI:1/4");
        assert!(EventPart::parse(&name, &payload).is_err());
    }

    #[test]
    fn rejects_bad_payload_len() {
        assert_eq!(
            EventPart::parse(b"SGN1:SIGN", &[0u8; 100]),
            Err(WireError::BadPayloadLen(100))
        );
    }
}
