# Always limit cluster tests to 4 threads
[test-groups]
cluster = { max-threads = 4 }
fixture = { max-threads = "num-cpus" }

[[profile.default.overrides]]
filter = 'test(cases::mpc) | test(cases::state_sync)'
test-group = 'fixture'

[[profile.default.overrides]]
filter = 'not (test(cases::mpc) | test(cases::state_sync))'
test-group = 'cluster'

# Usage: cargo nextest run -p integration-tests --profile fixture
[profile.fixture]
default-filter = 'test(cases::mpc) | test(cases::state_sync)'

# Usage: cargo nextest run -p integration-tests --profile cluster
[profile.cluster]
default-filter = 'not (test(cases::mpc) | test(cases::state_sync))'
