[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
docker-test = []
helios = ["mpc-node/helios"]

[dependencies]
alloy = { workspace = true, features = ["provider-anvil-api"] }

# solana dependencies
anchor-client.workspace = true
anyhow.workspace = true
async-process = "1"
async-trait.workspace = true
backon = "0.4"

# crypto dependencies
bip32 = "0.5.3"
bip39 = "2.2.0"
bollard = "0.17.0"
borsh.workspace = true
bs58 = "0.5.1"
cait-sith.workspace = true
ciborium.workspace = true
clap.workspace = true
deadpool-redis.workspace = true
ecdsa = "0.16.9"
elliptic-curve = { version = "0.13.8", default-features = false }
futures = "0.3"
generic-array = { version = "0.14.7", default-features = false }
hex.workspace = true
k256.workspace = true
mpc-contract.workspace = true

# local chain-signatures dependencies
mpc-crypto.workspace = true
mpc-keys.workspace = true
mpc-node = { path = "../chain-signatures/node", default-features = false, features = ["test-feature", "debug-page"] }
mpc-primitives.workspace = true

# near dependencies
near-account-id.workspace = true
near-crypto.workspace = true
near-fetch.workspace = true
near-jsonrpc-client = "0.15.1"
near-primitives.workspace = true
near-sdk.workspace = true

# if necessary, use the following branch for near related indexer hacking:
# { git = "https://github.com/near/near-workspaces-rs", branch = "phuong/tmp-node-2.3.0" }
near-workspaces.workspace = true
rand.workspace = true
reqwest.workspace = true
rlp.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
sha3.workspace = true
shell-escape = "0.1.5"
signet-program.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
solana-transaction-status.workspace = true
testcontainers = "0.23.1"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
anyhow.workspace = true
async-process = "1"
tokio.workspace = true

[dev-dependencies]
criterion = "0.5.1"
serial_test = "3"
test-log = { version = "0.2.12", features = ["log", "trace"] }

[[bench]]
name = "sign"
path = "benches/sign.rs"
harness = false

[[bench]]
name = "store"
path = "benches/store.rs"
harness = false
