name: Deploy Dev Smart Contract
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - develop
    paths:
      - 'chain-signatures/contract/**'

jobs:
  deploy-contract:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: add JSON contract
        run: mkdir -p ~/.near-credentials/testnet && echo '${{ secrets.DEV_CONTRACT_JSON }}' > ~/.near-credentials/testnet/dev.sig-net.testnet.json

      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install near-cli
        run: 'npm install -g near-cli'

      - name: Install Rust (1.93.0)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.93.0
          target: wasm32-unknown-unknown
          override: true

      - name: Install cargo-near
        run: |
          if ! command -v cargo-near >/dev/null; then
            curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
          fi

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: deploy-dev-contract
          cache-targets: true
          cache-on-failure: false

      - name: Build & Deploy Dev Contract
        run: |
          cargo near build non-reproducible-wasm --manifest-path chain-signatures/contract/Cargo.toml --no-abi --env 'RUSTFLAGS=-C link-arg=--allow-undefined'
          (yes || true) | near deploy dev.sig-net.testnet target/near/mpc_contract/mpc_contract.wasm
          near call dev.sig-net.testnet migrate '{}' --accountId dev.sig-net.testnet --gas 300000000000000
