name: Build Image & Deploy Nodes to Dev
on:
  push:
    branches:
      - develop
    paths:
      - chain-signatures/**
      - Cargo.*

env:
  IMAGE: "europe-west1-docker.pkg.dev/near-cs-dev/multichain-public/multichain-dev"
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: "Checkout mpc"

      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v4
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.SIG_CREDENTIALS_DEV }}

      - name: Build Docker image and push to Google Artifact Registry
        id: docker-push-tagged
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: "${{ env.IMAGE }}:${{ env.TAG }},${{ env.IMAGE }}:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SIG_CREDENTIALS_DEV }}'

