name: k6 Load Test

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    paths:
      - chain-signatures/**
  workflow_dispatch:

jobs:
  run-smoke:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          path: ./infra/loadtests/smoketest-dev.js
          cloud-run-locally: false
  run-long:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          path: ./infra/loadtests/2hour-dev.js
          cloud-run-locally: false