name: k6 Load Test

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    paths:
      - chain-signatures/**
      - infra/loadtests/**
      - .github/workflows/k6-ci-loadtest.yml
  workflow_dispatch:
    inputs:
      lt_strategy:
        type: choice
        options:
          - constant_low_rate_1h
          - constant_medium_rate_1h
          - constant_high_rate_1h
          - ramping_low_rate_1h
          - ramping_medium_rate_1h
          - ramping_high_rate_1h
        default: ramping_high_rate_1h
        required: true
      environment:
        type: choice
        options:
          - dev
          - testnet
          - mainnet
        default: dev
        required: true
      chain:
        type: choice
        options:
          - Solana
          - Ethereum
          - NEAR
        default: Solana
        required: true
      check_signature:
        type: boolean
        default: true
        required: true

jobs:
  load-test:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          LT_STRATEGY: ${{ github.event.inputs.lt_strategy }}
          LT_CHAIN: ${{ github.event.inputs.chain }}
          LT_CHAIN_ENV: ${{ github.event.inputs.environment }}
          LT_CHECK_SIGNATURE: ${{ github.event.inputs.check_signature }}
        with:
          path: ./infra/loadtests/k6-load-test.js
          cloud-run-locally: false
          cloud-comment-on-pr: true
          flags: --exit-on-running