name: Multichain Contract

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/multichain-contract.yml
      - chain-signatures/contract/**
      - chain-signatures/test-contracts/**

env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    name: MPC Contract Test
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-4x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1

      - name: Compile Contract
        run: cd ./chain-signatures && cargo build -p mpc-contract --target wasm32-unknown-unknown --release

      - name: Test Contract
        run: cd ./chain-signatures && cargo test -p mpc-contract --target x86_64-unknown-linux-gnu --release
        env:
          RUST_LOG: INFO
          RUST_BACKTRACE: 1
