name: Deploy Multichain Prod.
on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        options:
          - mainnet
          - testnet
        description: mainnet or testnet network
        default: testnet
        required: true
      image:
        description: Full Artifact Registry image with tag (e.g. us-east1-docker.pkg.dev/pagoda-discovery-platform-prod/multichain-public/multichain-< testnet | mainnet >)
        required: true
        default: us-east1-docker.pkg.dev/pagoda-discovery-platform-prod/multichain-public/multichain-testnet


jobs:
  build-mpc-recovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout mpc-recovery"

      - name: Login to GCP Artifact Registry
        run: echo "$GOOGLE_CREDENTIALS" | docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_PROD }}
      
      - name: Build Docker image and deploy partner nodes
        id: docker-push-tagged-partner
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile.multichain
          tags: "${{ github.event.inputs.image }}:latest"