name: Unit
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/unit.yml"
      - "chain-signatures/**/*.rs"
      - "chain-signatures/Cargo.*"
      - "integration-tests/**/*.rs"
      - "chain-signatures/contract-eth/**/*.sol"
      - "chain-signatures/contract-eth/**/*.js"
  pull_request:
  merge_group:

env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: warp-ubuntu-latest-x64-4x
    name: Check & Test
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust (1.81.0)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.81.0
          target: wasm32-unknown-unknown

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: chain-signatures/contract-eth/package-lock.json

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: unit-test
          cache-targets: true
          cache-on-failure: false
          # Prevent every PR from uploading multi-GB caches
          save-if: ${{ github.ref == 'refs/heads/develop' }}
      
      # Install system OpenSSL explicitly here so the build uses system OpenSSL instead of building OpenSSL from source
      - name: Install system OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      - name: Set OpenSSL to system
        run: echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
      
      - name: Compile Contract
        run: ./build-contract.sh
      
      - name: Compile eth contract
        run: cd chain-signatures/contract-eth && npm ci && npx hardhat compile
      
      - name: Eth contract unit tests
        run: cd chain-signatures/contract-eth && npx hardhat test
      
      - name: Test format
        run: cargo fmt -- --check
      
      - name: Test clippy
        run: cargo clippy --tests -- -Dclippy::all
      
      - name: Unit tests
        run: cargo test --workspace --exclude integration-tests

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.81.0

      # Run cargo-audit to check for vulnerable dependencies
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
