name: Workflow using the k6 run action
on:
  push:

jobs:
  verify-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
  env-var-test:
    runs-on: ubuntu-latest
    env:
      TEST_SYSTEM_ENV_VAR: "test-system-env-var-value"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - uses: ./
        with:
          path: |
            ./infra/loadtests/env-var-test.js
          flags: --vus 1 --duration 1s --env TEST_FLAG_ENV_VAR=test-flag-env-var-value -e TEST_SYSTEM_ENV_VAR_E=test-cli-e-env-var-value
