[package]
name = "threshold-ts"
version.workspace = true
edition = "2021"

[dependencies]
async-trait = "0.1"
cait-sith.workspace = true
mpc-node = { path = "../node" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
threshold-signatures = { git = "https://github.com/near/threshold-signatures", rev = "42c25b1674e5bc03a02ae462cf9b355f95fe9623" }
k256 = { version = "0.13.1", features = ["ecdsa", "sha256"] }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
rand = "0.8.5"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }