[package]
name = "mpc-contract"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
# utilized for benchmarking the node:
bench = []

[dependencies]
borsh.workspace = true
k256.workspace = true
mpc-crypto.workspace = true
mpc-primitives.workspace = true
near-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
digest = "0.10.7"

# crypto dependencies
ecdsa = { version = "0.16.9", features = ["digest", "hazmat"] }

# near dependencies
near-crypto.workspace = true
near-workspaces = "0.15.0"
rand.workspace = true
signature = "2.2.0"
tokio.workspace = true
